export enum WALLET_KIND {
  WALLET_PRIVATEKEY = 'WALLET_PRIVATEKEY',
  WALLET_METAMASK = 'WALLET_METAMASK',
  WALLET_METAMASK_SNAP = 'WALLET_METAMASK_SNAP',
  WALLET_MAGIC_LINK = 'WALLET_MAGIC_LINK',
  WALLET_CONNECT = 'WALLET_CONNECT'
}
